### ISSUE TITLE
Some WARCs lack bookmarks according to Webrecorder player

### ISSUE THREAD

**Issue by peterk** [N0taN3rd/node-warc#25]
Archived the following URL: https://www.facebook.com/socialdemokraternailjusdal/photos/a.1409766429240263/2084031858480380/?type=3&__xts__%5B0%5D=68.ARA3blS6QVatnljfKg2ED3yFCSVs2fEjWVC085o9H1oNPpiSDeld4Iu5HfWS59RvuteqLBXXBZZj0oN9I8r0S7RxjC_W77aYdiOtyPeaVCRfYm0O1rgzzqnYDIZTXDJEYPG-XJ0dpOoaGR8JI0JbP6NPCTYXaKKEPUUUKg1XihsVouag0W91ra3-Rqr-TpDrPm96rVOvgjIy8oe5Kse0ZV50kJ65pwWhKvBxm7bMoyTo1fsXAkK6sYdaM_iQhbT7PO25qk6VUbbrTlHSu5i7a3idF2huVM4KM7s-LaOZMPztninlNYMFjCjbJpOeK8wgNUrcXdzwPLsS3iYZ4-D4RcYwPSsU&__tn__=-R

Opening the resulting WARC in Webrecorder Player shows "No bookmarks available in the table":
<img width="379" alt="image" src="https://user-images.githubusercontent.com/19284/49794113-1f012f00-fd37-11e8-97c3-9aead52ca848.png">

Maybe the URL is too long or not escaped properly? Other (shorter) URLs seem to work fine.

Example zipped WARC file below.

[fbtest.warc.zip](https://github.com/N0taN3rd/node-warc/files/2667067/fbtest.warc.zip)

**Comment by peterk** [comment]
I am thinking this is a bug in Webrecorder player as it opens fine in openwayback.

**Comment by N0taN3rd** [comment]
This is definitively more of an issue with page detection rather than can play back.
Blind page discovery is hard... But we are looking into how to solve this issue.
Ref comment by @ikreymer in https://github.com/webrecorder/webrecorder-player/issues/77
